const TagOptions = [
    { value: 'eye care', label: 'eye care' },
    { value: 'free', label: 'free' },
    { value: 'open-source', label: 'open-source' },
    { value: 'photophobia', label: 'photophobia' },
    { value: 'computer filter', label: 'computer filter' },
    { value: 'visual processing', label: 'vision' },
    { value: 'sensory processing', label: 'sensory processing' },
    { value: 'technology', label: 'technology' },
    { value: 'desktop application', label: 'desktop application' },
    { value: 'mobile application', label: 'mobile application' },
    { value: 'blue-light filter', label: 'blue-light filter' },
    { value: 'tinted lenses/screen', label: 'tinted lenses/screen' },
    { value: 'font', label: 'font' },
    { value: 'reading', label: 'reading' },
    { value: 'light sensitivity', label: 'light sensitivity' },
    { value: 'vision', label: 'vision' },
    { value: 'dark mode', label: 'dark mode' },
    { value: 'newsletter', label: 'newsletter' },
    { value: 'case management', label: 'case management' },
    { value: 'support group', label: 'support group' },
    { value: 'referrals', label: 'referrals' },
    { value: 'support services', label: 'support services' },
    { value: 'check-ups', label: 'check-ups' },
    { value: 'peer-reviewed', label: 'peer-reviewed' },
    { value: 'articles', label: 'articles' },
    { value: 'scholarly', label: 'scholarly' },
    { value: 'scientific study', label: 'scientific study' },
    { value: 'workers compensation', label: 'workers compensation' },
    { value: 'lawyers', label: 'lawyers' },
    { value: 'financial', label: 'financial' },
    { value: 'settlement', label: 'settlement' },
    { value: 'file claim', label: 'fiile claim' },
    { value: 'consult', label: 'consult' },
    { value: 'motor vehicle accidents', label: 'motor vehicle accidents' },
    { value: 'car accident', label: 'car accident' },
    { value: 'benefits', label: 'benefits' },
    { value: 'advocate', label: 'advocate' },
    { value: 'brain fog', label: 'brain fog' },
    { value: 'tracking software', label: 'tracking software' },
    { value: 'memory care', label: 'memory care' },
    { value: 'medications', label: 'medications' },
    { value: 'habits', label: 'habits' },
    { value: 'scheduling', label: 'scheduling' },
    { value: 'calendar', label: 'calendar' },
    { value: 'symptom relief/management', label: 'symptom relief/management' },
    { value: 'medical', label: 'medical' },
    { value: 'marijuana dispensary', label: 'marijuana dispensary' },
    { value: 'overstimulation', label: 'overstimulation' },
    { value: 'de-stim', label: 'de-stim' },
    { value: 'migraine', label: 'migraine' },
    { value: 'pain relief', label: 'pain relief' },
    { value: 'drug', label: 'drug' },
    { value: 'hearing', label: 'hearing' },
    { value: 'ear care', label: 'ear care' },
    { value: 'noise sensitivity', label: 'noise sensitivity' },
    { value: 'decibals', label: 'decibals' },
    { value: 'PRN', label: 'PRN' },
    { value: 'pill case', label: 'pill case' },
    { value: 'rx prescriptions', label: 'rx prescriptions' },
    { value: 'pharmeceuticals', label: 'pharmeceuticals' },
    { value: 'supplements', label: 'supplements' },
    { value: 'headache', label: 'headache' },
    { value: 'migraine', label: 'migraine' },
    { value: 'hot cold', label: 'hot cold' },
    { value: 'nausea', label: 'nausea' },
    { value: 'post-concussion', label: 'post-concussion' },
    { value: 'glasses', label: 'glasses' },
    { value: 'journaling', label: 'journaling' },
    { value: 'planning', label: 'planning' },
    { value: 'therapy', label: 'therapy' },
    { value: 'treatment', label: 'treatment' },
    { value: 'medical doctor', label: 'medical doctor' },
    { value: 'physical rehabilitation', label: 'physical rehabilitation' },
    { value: 'speech therapy', label: 'speech therapy' },
    { value: 'recovery', label: 'recovery' },
    { value: 'ER', label: 'ER' },
    { value: 'dizzy/balance', label: 'dizzy/balance' },
    { value: 'trauma', label: 'trauma' },
    { value: 'orgnization', label: 'orgnization' },
    { value: 'PTSD', label: 'PTSD' },
    { value: 'DBT', label: 'DBT' },
    { value: 'CBT', label: 'CBT' },
    { value: 'chiropractor', label: 'chiropractor' },
    { value: 'back/neck pain', label: 'back/neck pain' },
    { value: 'scheduling', label: 'scheduling' },
  ]
  export default TagOptions;
